name: "${project.name}"
version: "${project.version}"
author: "MEFRREEX"
api: ["2.0.0"]
main: com.mefrreex.whitelister.Whitelister

depend:
  - "FormConstructor"
  - "JOOQConnector"

permissions:
  whitelister.command.whitelister:
    default: op
  whitelister.bypass:
    default: false